### PR TITLE
Add data of json file

### PR DESCRIPTION
**Pull request by imranhossainemi**
Project update: 
- Create  json files for authors, books, games, genres, labels, music_album
- Create item.rb file

### CODE REVIEW

**Review by Santosh-Konappanavar — CHANGES_REQUESTED** [review]
Hi @imranhossainemi , 

Good job so far!

There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Highlights
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 


#  *Status: Request changes* : 

- Fix the linters error.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Santosh-Konappanavar — APPROVED** [review]
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @imranhossainemi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Santosh-Konappanavar — APPROVED** [review]

**Comment by ikoote1** [comment]
But Imran you merged the branch (feature-branch) we were supposed to
submit.for review, into development, did they approve it before merging or
you just merged????

**Comment by ikoote1** [comment]
Please can you guys help and attend today's zoom call'

**Pull request merged**
